export const TICKET_FORM_LABELS = {
  PNR:                   "PNR * (6 characters)",
  AIRLINE:               "Airline *",
  FLIGHT_NUMBER:         "Flight Number *",
  TOTAL_SEATS:           "Total Seats *",
  AVAILABLE_SEATS:       "Available Seats *",
  DEPARTURE_LOCATION:    "Departure Location *",
  ARRIVAL_LOCATION:      "Arrival Location *",
  DATE_OF_JOURNEY:       "Date of Journey *",
  DEPARTURE_TIME:        "Departure Time *",
  ARRIVAL_TIME:          "Arrival Time *",
  PURCHASE_PRICE:        "Purchase Price *",
  TOTAL_PRICE:           "Total Price * (Auto)",
  DISCOUNT:              "Discount Price",
  SALE_PRICE:            "Sale Price *",
  ADVANCE_PAID:          "Advance Paid *",
  OUTSTANDING:           "Outstanding * (Auto)",
  PURCHASE_DATE:         "Purchase Date *",
  NAME_SUBMISSION_DATE:  "Name Submission Date *",
  OUTSTANDING_DATE:      "Outstanding Date *",
  JOURNEY_TYPE:          "Journey Type *",
  CLASS_TYPE:            "Class *",
  HAND_BAGGAGE:          "Hand Baggage",
  CHECKED_BAGGAGE:       "Checked Baggage",
  INFANT_FEES:           "Infant Fees",
};

export const TICKET_FORM_PLACEHOLDERS = {
  PNR:                   "e.g., ABC123",
  AIRLINE:               "Search airline...",
  FLIGHT_NUMBER:         "Enter flight number",
  SEATS:                 "e.g., 100",
  DEPARTURE_LOCATION:    "Search departure location...",
  ARRIVAL_LOCATION:      "Search arrival location...",
  PURCHASE_PRICE:        "e.g., 5000",
  TOTAL_PRICE:           "e.g., 6000",
  SALE_PRICE:            "e.g., 6500",
  ADVANCE_PAID:          "e.g., 2000",
  OUTSTANDING:           "e.g., 3000",
  HAND_BAGGAGE:          "e.g., 7kg",
  CHECKED_BAGGAGE:       "e.g., 15kg",
};

export const TICKET_FORM_VALIDATION = {
  PNR_REQUIRED:                  "PNR is required",
  PNR_LENGTH:                    "PNR must be exactly 6 characters",
  PNR_ALPHANUMERIC:              "PNR must be 6 alphanumeric characters (e.g., ABC123)",
  PNR_UNIQUE:                    "PNR must be unique",
  AIRLINE_REQUIRED:              "Airline is required",
  FLIGHT_NUMBER_REQUIRED:        "Flight number is required. Example: AI203",
  FLIGHT_NUMBER_WHITESPACE:      "Flight number cannot be empty or contain only spaces. Example: AI203",
  SEATS_REQUIRED:                "Total seats are required",
  AVAILABLE_SEATS_REQUIRED:      "Available seats are required",
  CANNOT_BE_NEGATIVE:            "Cannot be negative",
  CANNOT_EXCEED_TOTAL_SEATS:     "Cannot exceed total seats",
  DEPARTURE_LOCATION_REQUIRED:   "Departure location is required",
  ARRIVAL_LOCATION_REQUIRED:     "Arrival location is required",
  DATE_OF_JOURNEY_REQUIRED:      "Date of journey is required",
  DATE_IN_FUTURE:                "Date of journey must be today or a future date",
  PURCHASE_PRICE_REQUIRED:       "Purchase price is required",
  DATE_REQUIRED:                 "This date is required",
  DATE_BETWEEN:                  "Must be between purchase and journey date",
  TOTAL_PRICE_REQUIRED:          "Total price is required",
  PURCHASE_DATE_REQUIRED:        "Purchase date is required",
  JOURNEY_TYPE_REQUIRED:         "Journey type is required",
  CLASS_TYPE_REQUIRED:           "Class type is required",
};

export const TICKET_FORM_SECTIONS = {
  JOURNEY_DETAILS:   "Travel Journey Details",
  SCHEDULE_CLASS:    "Travel schedule & Class",
  PAYMENT_DETAILS:   "Payment Details",
  IMPORTANT_DATES:   "Important Dates",
  BAGGAGE_DETAILS:   "Baggage Details",
};

export const TICKET_FORM_BUTTONS = {
  BACK_TO_TICKETS:   "Back to Tickets",
  ADD_TICKET:        "Add Ticket",
  EDIT_TICKET:       "Edit Ticket",
  CANCEL:            "Cancel",
  UPDATE_TICKET:     "Update Ticket",
};

export const TICKET_FORM_OTHER = {
  ADD_NEW_TICKET:        "Add New Ticket",
  EDIT_TICKET_TITLE:     "Edit Ticket",
  CALCULATION_SUMMARY:   "Calculation Summary:",
  PURCHASE_PRICE:        "Purchase Price:",
  TOTAL_SEATS:           "Total Seats:",
  TOTAL_PRICE:           "Total Price:",
  ADVANCE_PAID:          "Advance Paid:",
  OUTSTANDING:           "Outstanding:",
  // BALANCE:           "Balance:",
};
